name = "NorahPhd"
uuid = "a7a6392f-c8bf-41a6-96d2-1e4213245d9e"
authors = ["Mohammed Alshahrani <mshahrani@kfupm.edu.sa", "NORAH ABDULLATIF ALMURAYSIL <g201901190@kfupm.edu.sa>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
